# Generated by Django 2.1.2 on 2018-11-08 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PermissoesMacropack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Permissão',
                'verbose_name_plural': 'Permissões',
                'permissions': (('macropack_permissoes', 'Permissão Global de Macropack'),),
                'managed': True,
            },
        ),
    ]
